THREESPACE_HEADER_STATUS_BIT_POS = 0
THREESPACE_HEADER_TIMESTAMP_BIT_POS = 1
THREESPACE_HEADER_ECHO_BIT_POS = 2
THREESPACE_HEADER_CHECKSUM_BIT_POS = 3
THREESPACE_HEADER_SERIAL_BIT_POS = 4
THREESPACE_HEADER_LENGTH_BIT_POS = 5
THREESPACE_HEADER_NUM_BITS = 6

THREESPACE_HEADER_STATUS_BIT = (1 << THREESPACE_HEADER_STATUS_BIT_POS)
THREESPACE_HEADER_TIMESTAMP_BIT = (1 << THREESPACE_HEADER_TIMESTAMP_BIT_POS)
THREESPACE_HEADER_ECHO_BIT = (1 << THREESPACE_HEADER_ECHO_BIT_POS)
THREESPACE_HEADER_CHECKSUM_BIT = (1 << THREESPACE_HEADER_CHECKSUM_BIT_POS)
THREESPACE_HEADER_SERIAL_BIT = (1 << THREESPACE_HEADER_SERIAL_BIT_POS)
THREESPACE_HEADER_LENGTH_BIT = (1 << THREESPACE_HEADER_LENGTH_BIT_POS)

THREESPACE_HEADER_FORMAT_CHARS = ['b', 'L', 'B', 'B', 'L', 'H']

FIRMWARE_VALID_BIT = 0x01

PASSIVE_CALIBRATE_GYRO = (1 << 0)
PASSIVE_CALIBRATE_MAG_REF = (1 << 1)

STREAMING_MAX_HZ = 2000

THREESPACE_OUTPUT_MODE_ASCII = 1
THREESPACE_OUTPUT_MODE_BINARY = 2

THREESPACE_GET_SETTINGS_ERROR_RESPONSE = "<KEY_ERROR>"
THREESPACE_BINARY_SETTINGS_ID_SIZE = 4
THREESPACE_BINARY_READ_SETTINGS_ID = 0xC695B5E1
THREESPACE_BINARY_WRITE_SETTINGS_ID = 0x822AAE18

THREESPACE_BINARY_WRITE_SETTING_RESPONSE_LEN = 3
THREESPACE_BINARY_WRITE_SETTING_WITH_HEADER_RESPONSE_LEN = THREESPACE_BINARY_SETTINGS_ID_SIZE + THREESPACE_BINARY_WRITE_SETTING_RESPONSE_LEN

THREESPACE_BINARY_READ_SETTINGS_START_BYTE = 0xFA
THREESPACE_BINARY_READ_SETTINGS_START_BYTE_HEADER = 0xFC

THREESPACE_BINARY_WRITE_SETTINGS_START_BYTE = 0xFB
THREESPACE_BINARY_WRITE_SETTINGS_START_BYTE_HEADER = 0xFD

#This is not comprehensive, just enough to separate keys from debug messages
THREESPACE_SETTING_KEY_INVALID_CHARS = " :;"

THREESPACE_FILE_STREAMING_MAX_PACKET_SIZE = 512
THREESPACE_LIVE_LOG_STREAM_MAX_PACKET_SIZE = 2048

THREESPACE_MAX_CMD_LEN = 2048

THREESPACE_SN_FAMILY_POS = 14 * 4
THREESPACE_SN_VARIATION_POS = 11 * 4
THREESPACE_SN_VERSION_POS = 10 * 4
THREESPACE_SN_MAJOR_REVISION_POS = 8 * 4
THREESPACE_SN_MINOR_REVISION_POS = 6 * 4
THREESPACE_SN_INCREMENTOR_POS = 0 * 4

THREESPACE_SN_FAMILY_MSK = 0xFF << THREESPACE_SN_FAMILY_POS
THREESPACE_SN_VARIATION_MSK = 0xFFF << THREESPACE_SN_VARIATION_POS
THREESPACE_SN_VERSION_MSK = 0xF << THREESPACE_SN_VERSION_POS
THREESPACE_SN_MAJOR_REVISION_MSK = 0xFF << THREESPACE_SN_MAJOR_REVISION_POS
THREESPACE_SN_MINOR_REVISION_MSK = 0xFF << THREESPACE_SN_MINOR_REVISION_POS
THREESPACE_SN_INCREMENTOR_MSK = 0xFFFFFF << THREESPACE_SN_INCREMENTOR_POS

THREESPACE_FAMILY_DEV = "DEV"
THREESPACE_FAMILY_USB = "USB"
THREESPACE_FAMILY_WIRELESS = "WL"
THREESPACE_FAMILY_EMBEDDED = "EM"
THREESPACE_FAMILY_BLUETOOTH = "BT"
THREESPACE_FAMILY_DATA_LOGGER = "DL"
THREESPACE_FAMILY_MICRO_USB = "MUSB"
THREESPACE_FAMILY_LX = "LX"

THREESPACE_SN_FAMILY_TO_NAME = {
    0x00 : THREESPACE_FAMILY_DEV,
    0x11 : THREESPACE_FAMILY_USB,
    0x12 : THREESPACE_FAMILY_WIRELESS,
    0x14 : THREESPACE_FAMILY_EMBEDDED,
    0x15 : THREESPACE_FAMILY_BLUETOOTH,
    0x16 : THREESPACE_FAMILY_DATA_LOGGER,
    0x17 : THREESPACE_FAMILY_MICRO_USB,
    0x21: THREESPACE_FAMILY_LX
}

THREESPACE_ERR_COMMIT_FS_LOCKED=8

THREESPACE_SELF_TEST_ERR_ACCEL = 0x01
THREESPACE_SELF_TEST_ERR_GYRO = 0x02
THREESPACE_SELF_TEST_ERR_MAG = 0x04
THREESPACE_SELF_TEST_ERR_BARO = 0x08
THREESPACE_SELF_TEST_ERR_RTC = 0x10
THREESPACE_SELF_TEST_ERR_GPS = 0x20
THREESPACE_SELF_TEST_ERR_BLUETOOTH = 0x40
THREESPACE_SELF_TEST_ERR_SD = 0x80
THREESPACE_SELF_TEST_ERR_SMS = 0x100
THREESPACE_SELF_TEST_ERR_BATTERY = 0x200

THREESPACE_DEBUG_LEVEL_ERR = 0x1  # An unexpected error has occurred, indicates something is not working as it should
THREESPACE_DEBUG_LEVEL_WRN = 0x2  # Warnings about issues that may affect accuracy, such as invalid segment detection
THREESPACE_DEBUG_LEVEL_INFO = 0x4  # Info for monitoring internal values and processes

THREESPACE_DEBUG_MODULE_MAIN = (1 << 0)
THREESPACE_DEBUG_MODULE_ASSERT = (1 << 1)
THREESPACE_DEBUG_MODULE_FLASH = (1 << 2)
THREESPACE_DEBUG_MODULE_SETTINGS = (1 << 3)
THREESPACE_DEBUG_MODULE_TIMER = (1 << 4)
THREESPACE_DEBUG_MODULE_SPI = (1 << 5)
THREESPACE_DEBUG_MODULE_GYRO = (1 << 6)
THREESPACE_DEBUG_MODULE_ACCEL = (1 << 7)
THREESPACE_DEBUG_MODULE_MAG = (1 << 8)
THREESPACE_DEBUG_MODULE_SENSORS = (1 << 9)
THREESPACE_DEBUG_MODULE_QGRAD2 = (1 << 10)
THREESPACE_DEBUG_MODULE_PWM = (1 << 11)
THREESPACE_DEBUG_MODULE_LED = (1 << 12)
THREESPACE_DEBUG_MODULE_BARO = (1 << 13)
THREESPACE_DEBUG_MODULE_EEPTS = (1 << 14)
THREESPACE_DEBUG_MODULE_INIT = (1 << 15)
THREESPACE_DEBUG_MODULE_SMS = (1 << 16)
THREESPACE_DEBUG_MODULE_PROTOCOL = (1 << 17)
THREESPACE_DEBUG_MODULE_COMMANDS = (1 << 18)
THREESPACE_DEBUG_MODULE_STREAM = (1 << 19)
THREESPACE_DEBUG_MODULE_INTERRUPT = (1 << 20)
THREESPACE_DEBUG_MODULE_RTC = (1 << 21)
THREESPACE_DEBUG_MODULE_ACALIB = (1 << 22)
THREESPACE_DEBUG_MODULE_WMM = (1 << 23)
THREESPACE_DEBUG_MODULE_FILTER = (1 << 24)
THREESPACE_DEBUG_MODULE_BLE = (1 << 25)
THREESPACE_DEBUG_MODULE_BUTTON = (1 << 26)
THREESPACE_DEBUG_MODULE_SD = (1 << 27)
THREESPACE_DEBUG_MODULE_GPS = (1 << 28)
THREESPACE_DEBUG_MODULE_BATTERY = (1 << 29)